### ISSUE TITLE
Cumulus upgrade to v16.1.1

### ISSUE THREAD

**Issue by jsrikish** [NASA-IMPACT/csdap-cumulus#265]
- [x] create a new v16.1.1 branch on github
- [x] Upgrade v13.4 to v16.1.1
- [x] Run smoke test
- [x] test cumulus with ORCA

**Comment by chuckwondo** [comment]
@jsrikish, @krisstanton, and I went over the Cumulus release notes from the version immediately following 13.4.0 (our current version) through 16.1.1. Offhand, it appears that our upgrade path _should_ be relatively smooth. Here are the pertinent points we extracted from the various release notes:

- Pull the latest code from our `main` branch and create a new branch named `cumulus-upgrade-16.1.1`
- [v14.0.0](https://github.com/nasa/cumulus/releases/tag/v14.0.0): No notable Terraform changes required
- [v14.1.0](https://github.com/nasa/cumulus/releases/tag/v14.1.0):
  - [ ] We manually upgraded PostgreSQL to v11 at the beginning of the year, but the latest "point" version at that time was 11.13. It is currently 11.18 (and AWS automatically upgrades point versions for us), so we will **bump the value of `engine_version` in `app/stacks/rds-cluster/main.tf` to match.**
- [v15.0.0](https://github.com/nasa/cumulus/releases/tag/v15.0.0)
  - [ ] Upgrade to latest Node 16.x version (set version inside the `.nvmrc` file)
  - [ ] Add the following block above the `module "cumulus"` block within `app/stacks/cumulus/main.tf`:
    ```plain
    data "aws_ecr_repository" "async_operation" {
      name = "async_operations"
    }
    ```
  - [ ] Add the following _inside_ of the `module "cumulus"` block within `app/stacks/cumulus/main.tf` (note that v15.0.0 sets the version number to 44, but the release notes for v16.1.1 bump it to 47):
    ```plain
    async_operation_image = "${data.aws_ecr_repository.async_operation.repository_url}:47"
    ```
- [v15.0.1](https://github.com/nasa/cumulus/releases/tag/v15.0.1): nothing to do
- [v15.0.2](https://github.com/nasa/cumulus/releases/tag/v15.0.2): nothing to do
- [v15.0.3](https://github.com/nasa/cumulus/releases/tag/v15.0.3): nothing to do
- [v15.0.4](https://github.com/nasa/cumulus/releases/tag/v15.0.4): nothing to do
- [v16.0.0](https://github.com/nasa/cumulus/releases/tag/v16.0.0): nothing to do (bump of version for `async_operation_image` is subsumed by change noted in v16.1.1)
- [v16.1.1](https://github.com/nasa/cumulus/releases/tag/v16.1.1):
  - [ ] Add the following _inside_ of the `module "cumulus"` block within `app/stacks/cumulus/main.tf`
    ```plain
    orca_api_uri = module.orca.orca_api_deployment_invoke_url
    orca_lambda_copy_to_archive_arn = module.orca.orca_lambda_copy_to_archive_arn
    orca_sfn_recovery_workflow_arn = module.orca.orca_sfn_recovery_workflow_arn
    ```
  - [ ] In `app/stacks/cumulus/main.tf`, find `module.orca.orca_lambda_copy_to_glacier_arn` and change the name to `module.orca.orca_lambda_copy_to_archive_arn`
  - [ ] In `config/helpers/cumulus_version_helper.rb` change `"v13.4.0"` to `"v16.1.1"`

After making all of the file changes above, do the following in a sandbox deployment:

- [ ] Run `make all-up-yes` (because we made a change in the rds-cluster module in addition to the changes in the cumulus module)
- [ ] Run smoke test
- [ ] If smoke test succeeds, open PR
