### ISSUE TITLE
Snyk high vulnerability: Nokogiri Heap-based Buffer Overflow

### ISSUE THREAD

**Issue by hbparache** [NASA-IMPACT/csdap-cumulus#397]
nokogiri
Heap-based Buffer Overflow
Vulnerability

Introduced through
terraspace@2.2.16
Fixed in
nokogiri@1.16.5
Exploit maturity
Proof of Concept
Show less detail 
Detailed paths
Introduced through: project@* › terraspace@2.2.16 › terraspace-bundler@0.5.0 › nokogiri@1.16.2
Fix: No remediation path available.
Security information
Factors contributing to the scoring:
Snyk: [CVSS v3.1 7.5](https://security.snyk.io/vuln/SNYK-RUBY-NOKOGIRI-7164639) - High Severity
NVD: Not available. NVD has not yet published its analysis.
[Why are the scores different? Learn how Snyk evaluates vulnerability scores](https://docs.snyk.io/features/fixing-and-prioritizing-issues/issue-management/severity-levels#understanding-snyks-vulnerability-analysis)
Overview
[nokogiri](https://nokogiri.org/) is a gem for parsing HTML, XML, SAX, and Reader.

Affected versions of this package are vulnerable to Heap-based Buffer Overflow through the xmlHTMLPrintFileContext function in xmllint.c. An attacker can read memory contents that may contain sensitive data by triggering a buffer over-read condition.

**Comment by krisstanton** [comment]
UPDATE:
nokogiri is defined in gemfile.lock at line 146.
Since this stems from gemfile.lock, as per the bottom of Chuck's comment here, https://github.com/NASA-IMPACT/csdap-cumulus/issues/396#issuecomment-2417099669, this is only part of the dev docker image and never gets exposed in anyway, so we can dis miss this ticket.
