### ISSUE TITLE
Debugging WV02 L2A SBX and UAT errors

### ISSUE THREAD

**Issue by jsrikish** [NASA-IMPACT/csdap-cumulus#415]
While setting up the WV02_L2A Dataset, we are seeing the following errors

(1) In Sandbox, during test ingest, we have an error at the `CopyToArchive` Step
- Possible Solution -- Rotate the ORCA Credentials for DR UAT

(2) In UAT, We are getting an internal 500 error when running the command to add the new rules for the WV02 L2A Dataset
- Possible Solution 

- [x] Check to ensure the Collection was added first

- [x] Check the previous rules enable & run
       cumulus rules enable--name PSScene3Band___1_SmokeTest
       cumulus rules run --name PSScene3Band___1_SmokeTest
       (Got the same Access Denied --orca copy to archive) 

Error Details
```
DOTENV=.env.cba.uat make bash

...
 // Docker Init Items
...

/rules returned 500: {"statusCode":500,"error":"Internal Server Error","message":"An internal server error occurred"}
/rules returned 500: {"statusCode":500,"error":"Internal Server Error","message":"An internal server error occurred"}
/rules returned 500: {"statusCode":500,"error":"Internal Server Error","message":"An internal server error occurred"}
ERROR: /rules returned 500: {"statusCode":500,"error":"Internal Server Error","message":"An internal server error occurred"}

```

**Comment by krisstanton** [comment]
Cleaned up the description of the ticket a bit.
We are still working on troubleshooting this one.

**Comment by hbparache** [comment]
Added WV02 MSI L2A in MMT UAT

**Comment by krisstanton** [comment]
WIP Update: 
On Issue 2, we are now able to get the rules added.  It looks like this might have just been a network / connection issue from yesterday.

**Comment by aliziel** [comment]
Might have a lead:

On 2024-08-12 an `NGAPProtCircuitBreaker` role updated the bucket policies for all private DR UAT buckets to explicitly deny `(Get|Put|Replicate|Restore)Object` actions. This seems to line up with the last successful ingest workflows. 

I haven't come across this in my travels yet, but given the information available it looks like an expected response to a lockdown-type event. That circuit breaker role is attached to an account ending in -3509 though, in case we need to investigate this further.

**Comment by krisstanton** [comment]
@aliziel 
Thank you for this lead!
I don't know how you found this but I think you saved the day here!  
I went in and removed (temporarily) the section of the policy you referred to in order to see if Sandbox and UAT smoke tests work.
So far the Sandbox one Passed!  I am in the process of doing a UAT deployment, via PR 418 https://github.com/NASA-IMPACT/csdap-cumulus/pull/418 to run this same test in UAT.  If it passes there too, then we need @jsrikish to re-run the small WV02 L2A test she was originally trying to run.  If that works, then I'll be reinstating the policy for UAT because they may have put that in there for an important reason that we are currently unaware of.

**Comment by krisstanton** [comment]
Update: Smoke test in UAT Passed.  Also Verified that PROD still works (Small migration ingest all worked as expected).
All we need now is to re-run the WV02 L2A part

**Comment by krisstanton** [comment]
Update:  We were able to get WV02 L2A granules passed the CopyToArchive step! 
Closing this ticket now.
